"""Pure wizard state helpers (headless-test friendly).

Contains first-run detection, config writing, and marker logic that
do not depend on GTK / gi.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from .config import Config

log = logging.getLogger(__name__)

_MARKER_FILE = ".wizard-done"

# ASR backend descriptions shown in the wizard.
ASR_BACKENDS = [
    (
        "sherpa",
        "Sherpa-ONNX",
        "Fast ONNX-based streaming ASR.  Works on CPU — no GPU needed.",
    ),
    (
        "nemo",
        "NeMo (NVIDIA)",
        "Highest accuracy streaming ASR.  Requires an NVIDIA GPU with CUDA.",
    ),
    (
        "moonshine",
        "Moonshine-ONNX",
        "Lightweight ONNX ASR with low resource usage.  CPU-friendly.",
    ),
]

# Keybind presets for push-to-talk setup.
# (id, display_label, hyprland_bind_key_spec, description)
# hyprland_bind_key_spec is the "MODS, KEY" portion for bind/bindr lines.
KEYBIND_PRESETS = [
    ("f9", "F9", ", F9", "Simple single-key push-to-talk."),
    (
        "super_v",
        "Super + V",
        "SUPER, V",
        "Modifier combo — mnemonic for Voice.",
    ),
    (
        "scroll_lock",
        "Scroll Lock",
        ", Scroll_Lock",
        "Dedicated key, no modifier needed.",
    ),
    ("custom", "Custom", None, "Set your own key in Hyprland config later."),
]


def format_hyprland_bind(hypr_key_spec: str) -> str:
    """Format Hyprland bind/bindr lines for a push-to-talk keybind."""
    return (
        f"bind = {hypr_key_spec}, exec, shuvoice --control start\n"
        f"bindr = {hypr_key_spec}, exec, shuvoice --control stop"
    )


def needs_wizard() -> bool:
    """Return True when the welcome wizard should run (first launch).

    Returns False if the wizard-done marker exists **or** if a config.toml
    already exists (upgrade path — existing installations should not be
    forced through the wizard just because the marker is absent).
    """
    if (Config.data_dir() / _MARKER_FILE).exists():
        return False
    if (Config.config_dir() / "config.toml").exists():
        return False
    return True


def write_marker():
    """Create the .wizard-done marker so the wizard won't run again."""
    marker = Config.data_dir() / _MARKER_FILE
    marker.write_text("done\n")


def _upsert_asr_backend(config_file: Path, asr_backend: str):
    """Update or insert ``asr_backend`` under ``[asr]`` in config.toml.

    Preserves unrelated lines/comments and only patches the relevant field.
    """
    lines = config_file.read_text().splitlines(keepends=True)

    section_re = re.compile(r"^\s*\[([^\]]+)\]\s*$")
    key_re = re.compile(r"^\s*asr_backend\s*=")

    asr_start: int | None = None
    asr_end = len(lines)

    for idx, line in enumerate(lines):
        match = section_re.match(line.strip())
        if not match:
            continue
        section_name = match.group(1).strip().lower()
        if asr_start is None:
            if section_name == "asr":
                asr_start = idx
            continue
        asr_end = idx
        break

    new_line = f'asr_backend = "{asr_backend}"\n'

    if asr_start is None:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += "\n"
        if lines and lines[-1].strip():
            lines.append("\n")
        lines.extend(["[asr]\n", new_line])
        config_file.write_text("".join(lines))
        return

    for idx in range(asr_start + 1, asr_end):
        stripped = lines[idx].lstrip()
        if stripped.startswith("#"):
            continue
        if key_re.match(stripped):
            indent = lines[idx][: len(lines[idx]) - len(lines[idx].lstrip())]
            lines[idx] = f"{indent}{new_line}"
            config_file.write_text("".join(lines))
            return

    insert_at = asr_start + 1
    while insert_at < asr_end and lines[insert_at].strip().startswith("#"):
        insert_at += 1
    lines.insert(insert_at, new_line)
    config_file.write_text("".join(lines))


def write_config(asr_backend: str, *, overwrite_existing: bool = False):
    """Write wizard selections to config.toml.

    By default, preserves existing config files. When ``overwrite_existing`` is
    true, only ``[asr].asr_backend`` is updated in-place.
    """
    config_file = Config.config_dir() / "config.toml"
    if config_file.exists():
        if not overwrite_existing:
            log.info("config.toml already exists; wizard will not overwrite it")
            return
        _upsert_asr_backend(config_file, asr_backend)
        log.info("Updated asr_backend in %s", config_file)
        return

    lines = [
        "# Generated by ShuVoice welcome wizard\n",
        "\n",
        "[asr]\n",
        f'asr_backend = "{asr_backend}"\n',
    ]
    config_file.write_text("".join(lines))
    log.info("Wrote %s", config_file)


def format_summary(asr_backend: str, keybind_id: str = "f9") -> str:
    """Build a human-readable summary of wizard selections."""
    asr_name = next(
        (label for bid, label, _ in ASR_BACKENDS if bid == asr_backend),
        asr_backend,
    )
    keybind_label, hypr_key = next(
        ((label, hk) for kid, label, hk, _ in KEYBIND_PRESETS if kid == keybind_id),
        ("Custom", None),
    )

    lines = [
        f"ASR backend:    {asr_name}",
        f"Push-to-talk:   {keybind_label}",
    ]

    if hypr_key:
        bind_lines = format_hyprland_bind(hypr_key)
        indented = "\n".join(f"  {line}" for line in bind_lines.splitlines())
        lines.extend(
            [
                "",
                "Add to ~/.config/hypr/hyprland.conf:",
                "",
                indented,
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Configure your keybind in ~/.config/hypr/hyprland.conf",
                "See README.md for bind/bindr examples.",
            ]
        )

    return "\n".join(lines)
