"""Pure wizard state helpers (headless-test friendly).

Contains first-run detection, config writing, and marker logic that
do not depend on GTK / gi.
"""

from __future__ import annotations

import logging

from .config import Config

log = logging.getLogger(__name__)

_MARKER_FILE = ".wizard-done"

# ASR backend descriptions shown in the wizard.
ASR_BACKENDS = [
    (
        "nemo",
        "NeMo (NVIDIA)",
        "Highest accuracy streaming ASR.  Requires an NVIDIA GPU with CUDA.",
    ),
    (
        "sherpa",
        "Sherpa-ONNX",
        "Fast ONNX-based streaming ASR.  Works on CPU \u2014 no GPU needed.",
    ),
    (
        "moonshine",
        "Moonshine-ONNX",
        "Lightweight ONNX ASR with low resource usage.  CPU-friendly.",
    ),
]

HOTKEY_BACKENDS = [
    ("evdev", "evdev", "Listen for key events via /dev/input (default, requires permissions)."),
    ("ipc", "IPC socket", "Control recording via Hyprland keybind \u2192 shuvoice --control."),
]


def needs_wizard() -> bool:
    """Return True when the welcome wizard should run (first launch).

    Returns False if the wizard-done marker exists **or** if a config.toml
    already exists (upgrade path — existing installations should not be
    forced through the wizard just because the marker is absent).
    """
    if (Config.data_dir() / _MARKER_FILE).exists():
        return False
    if (Config.config_dir() / "config.toml").exists():
        return False
    return True


def write_marker():
    """Create the .wizard-done marker so the wizard won't run again."""
    marker = Config.data_dir() / _MARKER_FILE
    marker.write_text("done\n")


def write_config(asr_backend: str, hotkey_backend: str):
    """Write a minimal config.toml with the wizard selections.

    Does nothing if config.toml already exists to avoid clobbering
    user edits.
    """
    config_file = Config.config_dir() / "config.toml"
    if config_file.exists():
        log.info("config.toml already exists; wizard will not overwrite it")
        return

    lines = [
        "# Generated by ShuVoice welcome wizard\n",
        "\n",
        "[asr]\n",
        f'asr_backend = "{asr_backend}"\n',
        "\n",
        "[hotkey]\n",
        f'hotkey_backend = "{hotkey_backend}"\n',
    ]
    config_file.write_text("".join(lines))
    log.info("Wrote %s", config_file)


def format_summary(asr_backend: str, hotkey_backend: str) -> str:
    """Build a human-readable summary of wizard selections."""
    asr_name = next(
        (label for bid, label, _ in ASR_BACKENDS if bid == asr_backend),
        asr_backend,
    )
    hk_name = next(
        (label for bid, label, _ in HOTKEY_BACKENDS if bid == hotkey_backend),
        hotkey_backend,
    )
    return (
        f"ASR backend:    {asr_name}\n"
        f"Hotkey backend: {hk_name}\n"
        f"Hotkey:         Right Ctrl (KEY_RIGHTCTRL)"
    )
